$('#HomePage').toUI('homepage');
$('#start-btn').toUI('startbtn');
$('#gamearea').toUI('gamearea');
$('#pause-btn').toUI('pausebtn');
$('#pause-page').toUI('pausepage');
$('#continue-btn').toUI('continuebtn');
$( "#sprite" ).toSprite('sprite');
$( "#sprite" ).toSprite('control', '10,10');
$( "#sprite" ).teleport('', 100, 200);
$('#enemy').toSprite('enemy');
$('#enemy').teleport('', 200, 200);