$('#HomePage').toUI('homepage');
$('#start-btn').toUI('startbtn');
$('#gamearea').toUI('gamearea');
$('#pause-btn').toUI('pausebtn');
$('#pause-page').toUI('pausepage');
$('#continue-btn').toUI('continuebtn');
$('#santa-fight').toUI('fightpage', 'santa');
$('#save-btn').toUI('savebtn');
$( '#sprite' ).toSprite('sprite');
$( '#sprite' ).toSprite('control', '10,10');
$( '#sprite' ).teleport('', 100, 200);
$('#santa').toSprite('enemy', 'santa');
$('#santa').teleport('', 200, 200);